@base_url = http://localhost:3000

###
GET {{base_url}}/api/hello
Content-Type: application/json

###
POST {{base_url}}/api/hello
Content-Type: application/json

{
  "name": "John"
}

###
PUT {{base_url}}/api/hello/1
Content-Type: application/json

{
  "name": "John"
}

###
PATCH {{base_url}}/api/hello/1
Content-Type: application/json

{
  "name": "John"
}

###
DELETE {{base_url}}/api/hello/1
Content-Type: application/json
