---
networks:
  api-service-network:

volumes:
  grafana-data:
  loki-data:

services:
  loki:
    image: grafana/loki:3.7.8
    container_name: ${PROJECT_NAME}_loki
    command:
      - -config.file=/etc/loki/config.yaml
    volumes:
      - ../../observability/loki/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki
    environment:
      LOG_LEVEL: info
    ports:
      - "${LOKI_PORT:-3100}:3100"
    networks:
      - api-service-network

  alloy:
    image: grafana/alloy:v1.19.2
    container_name: ${PROJECT_NAME}_alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "${ALLoy_PORT:-12345}:12345"
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - ../../observability/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - api-service-network

  grafana:
    image: grafana/grafana:12.4.11
    container_name: ${PROJECT_NAME}_grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning

    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../../observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
      - alloy
    restart: always
    networks:
      - api-service-network
