apiVersion: 1

policies:
  - orgId: 1
    receiver: ticket
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: page
        object_matchers:
          - ['severity', '=', 'critical']
        group_by:
          - alertname
          - service
          - route
          - code
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: ticket
        object_matchers:
          - ['severity', '=', 'warning']
        group_by:
          - alertname
          - service
          - route
          - constraint
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
