---
networks:
  base-api-service-network:
    driver: bridge

volumes:
  database-data:

services:
  # ---------------------------------------------------------------------
  # | Node.js API Service                                               | 
  # ---------------------------------------------------------------------
  api-service:
    container_name: ${COMPOSE_PROJECT_NAME}_api_service
    build:
      context: ./${API_SERVICE_PROJECT_PATH}
      dockerfile: Dockerfile.dev
      args:
        - NODE_PORT=${NODE_PORT}
    ports:
      - "3002:${NODE_PORT}"
    depends_on:
      - database
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ./${API_SERVICE_PROJECT_PATH}:/usr/src/app
    networks:
      - base-api-service-network

  # ---------------------------------------------------------------------
  # | Postgres Database                                                 |
  # ---------------------------------------------------------------------
  database:
    image: postgres:18
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./${DATABASE_PROJECT_PATH}/seeds/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - base-api-service-network

  # ---------------------------------------------------------------------
  # | PgAdmin                                                           |
  # ---------------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    # ensure that the CONTAINER user id and group id are the same as the HOST user id and group id
    # without this, the container will fail to write files to the host volume
    # user: "${HOST_USER_ID}:${HOST_GROUP_ID}"
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - database
    restart: always
    entrypoint: >
      /bin/sh -c "
      echo 'database:5432:*:${DATABASE_USER}:${DATABASE_PASSWORD}' > /tmp/pgpass &&
      chmod 600 /tmp/pgpass &&
      /entrypoint.sh
      "
    networks:
      - base-api-service-network
    volumes:
      # - ./database/.tmp-data/${PROJECT_NAME}-data/:/var/lib/pgadmin/
      - ./${DATABASE_PROJECT_PATH}/pgAdmin/config_distro.py:/pgadmin4/config_distro.py
      - ./${DATABASE_PROJECT_PATH}/pgAdmin/servers.json:/pgadmin4/servers.json:ro