apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse
    isDefault: true
    editable: false
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: $CLICKHOUSE_USER
      defaultDatabase: $CLICKHOUSE_DB
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
